name: earthml
channels:
  - defaults
dependencies:
  - python=3.6
  - notebook=5.7.8
  - ipykernel=5.1.0
  - nomkl
  - bokeh=1.1.0
  - cartopy=0.17.0
  - geoviews=1.6.2
  - holoviews=1.12.3
  - numpy=1.16.3
  - pandas=0.24.2
  - rasterio
  - xarray=0.12.1
  - numba =0.42.0
  - colorcet
  - dask
  - dask-ml
  - datashader ==0.7.0
  - intake
  - intake-xarray
  - hvplot
  - s3fs